#include "MainWindow.h"

/*
	---------ROADMAP FOR THE PROJECT-------------
	MOVE EDGE DETECTION METHODS TO FEAT.H -- DONE
	ADD THE LAST EDGE OPERATOR -DERICHE- FORGOT ITS NAME -- SKIPPED BUT COME BACK
	ADD CORNER DETECTION -- SKIP NO TIME
	ADD KEYPOINT DETECTION -- SKIPPED BUT DO COME BACK
	ASK STACKOVERFLOW QUESTION ABOUT FFT OUTPUT BEING USELESS -- EZ SOLVED
	ADD HASHING -- EZ DONE BUT IS USELESS
	BUILD MACHINE LEARNING -- COME BACK TO IT
	ASK SO ABOUT XXHASH VALUES BEING DIFFERENT -- NVM FIXED
	BUILD THE DATABASE DETAILS WILL FOLLOW -- BUILD IN COOP WITH GUI
	BUILD GUI DETAILS WILL FOLLOW -- HERE ARE THE DETAILS
		VISUALISE THE GUI - BY GRAPHITE PENCIL(OR WHATEVER KUR�UN KALEM IN ENG IS) IF YOU HAVE TO -- DONE I SUPPOSE
		PLACE ALL THE BUTTONS AND TABS -- DONEISH 
		ADD FUNCTIONS TO THOSE OBJECTS
		DONT USE DEFINITE SIZE USE RATIOS
		ASK SOME QUESTIONS ON SO
			WHY IS TABLEVIEW SHOWING A BOX INSTEAD OF STRING
			WHY IS TABLEVIEW HEADER STRING FAULTY
			WHY IS TABLEVIEW LAGGY
		GO BACK TO LINKER.CPP LINE 29 AND INSERT TO ICONIMAGE
	ADD UHMMMMM WHAT WAS IT YES EDGE COMPARISON METHODS AND MAYBE CORNER ASWELL -- SKIP BUT MUST COME BACK YOU HEAR? MUST
	CHANGE RESIZE PARAMETERS AT DBOP::INSERT_IMAGE FUNCTION -- DONE
	LETS NOT FORGET MULTI THREADING -- DONE AND DUSTED
	CHECK IF POINTERS BE CRAZY AT CORNER HARRIS LAPLACE -- DONE
	MAKE CORNER COLOR AND RADIUS CUSTOMIZABLE -- NAH
	IF GRAY DISABLE SECOND AND THIRD BIN -- DONE
	IF NOT ENABLED DISABLE ALL WIDGETS -- DONEY
	PUT RAW COMPARISON VALUES INTO DATABASE !!!!!!!!!!!!!!!HIGH PRIORITY --DONE
	MAKE DIR AN ALTERNATE COLUMN TO ICONS !!!!!!!!!! -- LOL SO IMPORTANT

	ADD MULTIPLE DELETING OF IMAGES
	ADD ZOOMER FUNC TO PAGE 2 --EVENTUALLY
	CHANGE SERIALIZATION TO CV MAT'S
	MAKE IT POSSIBLE THAT CHANGING FEATURE VECTOR ELEMENTS DONT NEED COMPLETE RECALCULATION
	NORMALIZE DIFFERENCE VALUES
	ADD DIFFERENCE TO AVERAGE IN DETAILS
	MAKE IT SO DETAILS TAB DOESNT GET FULL FOCUS, CAN STILL TO STUFF AT MAINWINDOW
	-WHILE ITS OPEN OR WHATEVER
	MULTI THREAD IMAGE LOADING
	https://doc.qt.io/qt-5/qcontiguouscache.html
	HASH COMPARISON

	FINISH UNIVERSITY -- ALMOST THERE AS OF 20.03.2021 M8 - ONE STAJ TO GO
	GET A 15K DOLLAR PER MONTH JOB
	FINISH LIFE

	bune amk	-Enes kardeş
*/

int main(int argc, char* argv[])
{
	AllocConsole();
	auto ohye = freopen("conin$", "r", stdin);
	ohye = freopen("conout$", "w", stdout);  //DELETE IN FINAL BUILD THIS WHOLE SEGMENT
	ohye = freopen("conout$", "w", stderr);
	
	dbop::Database db("bitirme.db");
	lnkr::setDatabaseClass(db);

	QApplication a(argc, argv);
	MainWindow w = MainWindow(db);
	while (true) {
		try {
			w.show();
			return a.exec();
		}
		catch (gen::Warning e) {
			w.showWarning(e.code.c_str());
			continue;
		}
		catch (const std::exception& e) {
			w.showError(e.what());
			continue;
		}
	}
}